### ISSUE TITLE
Implementation of ImageNet-30

### ISSUE THREAD

**Issue by seekingup** [nukezil/IOMatch#2]
Hello, thanks for the interesting work and code. I am trying to run the ImageNet-30, which however is not included in the current version. Could you kindly share the yaml files or some detailed hyper-parameters?

**Comment by nukezil** [comment]
Thanks for your interest in our work! We have update the corresponding configs (see `./config/openset_cv/iomatch/iomatch_in30_p1/5_1.yaml` and it is easy to generate configs with other seeds) and data splits (see `./data/imagenet30/filelist`) for ImageNet-30 benchmark. Please check the file links in the updated README to prepare the dataset. 

As can be seen in these configs, we adopted the shadow network and small batch sizes to accelerate the experiments due to the original conference deadline. We will rerun the experiments with a deeper backbone and larger batch sizes in an extended journal version.

Please feel free to contact me if you have further concerns.

**Comment by seekingup** [comment]
thanks for sharing!

**Comment by seekingup** [comment]
hello, I reproduced the results for ImageNet-30 1% of IOMatch, and the accuracy is 69.45%, which matches the accuracy reported in the paper.

As you mentioned, it is true that the current results are not optimal. When I change the num_train_iter to 262144, the accuracy can be improved to 77.80%.
Thanks again for your help! Good luck for the journal version!

**Comment by nukezil** [comment]
We deeply appreciate your ongoing interest! We will make every effort to further enhance our work. Best wishes to you!
